name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Set Identity
      run: |
        git config --global user.email "githubactions@codyhoover.com"
        git config --global user.name "Github Actions"
    - name: Deploy to GH Pages
      run: npm run deploy --silent --repo "https://$x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"